### PR TITLE
!!! TASK: refactor the package to mixins approach

### PR DESCRIPTION
**Pull request by dimaip**
Do not set mixins by default on the `Neos.Neos:Document` nodetype and do not automatically include metatags rendering to `Neos.Neos:Page` prototype, instead of that provide the base mixins and document how to use them.

### CODE REVIEW

**Comment by dimaip** [comment]
Somebody notice me!

**Comment by kdambekalns** [comment]
I totally love the refactoring, great job!

What I am unsure about is the change in behaviour… Before the package was "activated automagically", now manual action is needed, for what I consider the majority of users.

Is this worth it?

**Comment by kdambekalns** [comment]
I merged master & did some stylistic tweaks, see https://github.com/dimaip/neos-seo/pull/1

I am still unsure about the behaviour change, which requires us to make the next version 3.0.0. I'd suggest to leave that part unchanged… see https://github.com/dimaip/neos-seo/pull/2 (includes the tweaks from https://github.com/dimaip/neos-seo/pull/1 as well)

**Comment by dfeyer** [comment]
I push an other PR, because I can push to this one
https://github.com/neos/neos-seo/pull/52

- Solved the conflict, by upmerging master

**Pull request closed without merging**
