### PR TITLE
TASK: Rename setting ``typoScript.autoInclude`` to ``fusion.autoInclude``

### PR DESCRIPTION
**Pull request by mficzel**
Additionally the existing core-migrations are marked as applied.

### CODE REVIEW

**Comment by aertmann** [comment]
maybe the migration which does this should be added to composer.json?

**Comment by mficzel** [comment]
@aertmann ... i simply ran the migrations

**Comment by aertmann** [comment]
thanks! looks good now

**Comment by mficzel** [comment]
Shall we merge this now. We will have to tag a release for the beta so this should go in soonish.

**Pull request merged**
